version: '3'
services:
    mysql:
        image: mysql
        ports:
            - 3307:3306
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: movies

